# Generated by Django 5.2.3 on 2025-06-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_itineraries',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
