# Generated by Django 5.2.3 on 2025-06-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Your maximum budget in ₹', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_info', to='planner.trip'),
        ),
    ]
